### ISSUE TITLE
Add timer controls

### ISSUE THREAD

**Issue by Wellingborough** [Wellingborough/backtracking-project#7]
It would be nice to have a speed control on the UI; either speed up/slow down buttons, or perhaps a slider to set the move piece interval.

**Comment by jesusdoza** [comment]
just saw this issue and wondered if it's okay to use vanilla javascript for the slider and Html/CSS?

**Comment by Wellingborough** [comment]
Absolutely!  I see that you have forked the project - I’ll take a look tomorrow.  Thanks for your interest.

**Comment by jesusdoza** [comment]
I just put the bare functionality of changing the delay but I could change the appearance of the slider and position
